apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-mdm.openshift-operators: ''
      manager: catalog
      operation: Update
  name: {{ .Values.match360mdmoper.subscription.name }}
  namespace: openshift-operators
spec:
  {{- toYaml .Values.match360mbmoper.subscription | nindent 2 }}

