apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-mdm.openshift-operators: ''
  name: {{ .Values.subscriptions.match360mdmoper.name }}
  namespace: openshift-operators
spec:
  {{- toYaml .Values.subscriptions.match360mdmoper.subscription | nindent 2 }}
